#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_URL="${CLACK_REPO_URL:-https://github.com/bombshell-dev/clack.git}"
SOURCE_PATH="${1:-}"
TEMP_SOURCE=""

cleanup() {
  if [[ -n "$TEMP_SOURCE" && -d "$TEMP_SOURCE" ]]; then
    rm -rf "$TEMP_SOURCE"
  fi
}

trap cleanup EXIT

if [[ -z "$SOURCE_PATH" ]]; then
  TEMP_SOURCE="$(mktemp -d "${TMPDIR:-/tmp}/clack-sync.XXXXXX")"
  git clone --depth 1 "$REPO_URL" "$TEMP_SOURCE"
  SOURCE_PATH="$TEMP_SOURCE"
fi

if [[ ! -d "$SOURCE_PATH" ]]; then
  echo "Source path not found: $SOURCE_PATH" >&2
  exit 1
fi

DOCS_DIR="$SKILL_DIR/references/docs"
CORE_DIR="$SKILL_DIR/references/source/core"
PROMPTS_DIR="$SKILL_DIR/references/source/prompts"
EXAMPLES_DIR="$SKILL_DIR/references/examples"
INDEX_FILE="$SKILL_DIR/references/INDEX.md"

mkdir -p "$DOCS_DIR" "$CORE_DIR" "$PROMPTS_DIR" "$EXAMPLES_DIR"

cp "$SOURCE_PATH/README.md" "$DOCS_DIR/clack-root-readme.md"
cp "$SOURCE_PATH/package.json" "$DOCS_DIR/clack-root-package.json"
cp "$SOURCE_PATH/packages/core/README.md" "$DOCS_DIR/core-readme.md"
cp "$SOURCE_PATH/packages/core/package.json" "$DOCS_DIR/core-package.json"
cp "$SOURCE_PATH/packages/core/src/index.ts" "$DOCS_DIR/core-exports.ts"
cp "$SOURCE_PATH/packages/prompts/README.md" "$DOCS_DIR/prompts-readme.md"
cp "$SOURCE_PATH/packages/prompts/package.json" "$DOCS_DIR/prompts-package.json"
cp "$SOURCE_PATH/packages/prompts/src/index.ts" "$DOCS_DIR/prompts-exports.ts"

cp -R "$SOURCE_PATH/packages/core/src/." "$CORE_DIR/"
cp -R "$SOURCE_PATH/packages/prompts/src/." "$PROMPTS_DIR/"
cp -R "$SOURCE_PATH/examples/." "$EXAMPLES_DIR/"

{
  echo "# Clack References Index"
  echo
  echo "Generated by \`scripts/sync_references.sh\`."
  echo
  echo "## Docs"
  while IFS= read -r path; do
    rel="${path#$SKILL_DIR/}"
    echo "- \`$rel\`"
  done < <(find "$DOCS_DIR" -type f | sort)
  echo
  echo "## Core Source"
  while IFS= read -r path; do
    rel="${path#$SKILL_DIR/}"
    echo "- \`$rel\`"
  done < <(find "$CORE_DIR" -type f | sort)
  echo
  echo "## Prompts Source"
  while IFS= read -r path; do
    rel="${path#$SKILL_DIR/}"
    echo "- \`$rel\`"
  done < <(find "$PROMPTS_DIR" -type f | sort)
  echo
  echo "## Examples"
  while IFS= read -r path; do
    rel="${path#$SKILL_DIR/}"
    echo "- \`$rel\`"
  done < <(find "$EXAMPLES_DIR" -type f | sort)
} > "$INDEX_FILE"

DOC_COUNT=$(find "$DOCS_DIR" -type f | wc -l | tr -d ' ')
CORE_COUNT=$(find "$CORE_DIR" -type f | wc -l | tr -d ' ')
PROMPTS_COUNT=$(find "$PROMPTS_DIR" -type f | wc -l | tr -d ' ')
EXAMPLE_COUNT=$(find "$EXAMPLES_DIR" -type f | wc -l | tr -d ' ')

echo "Synced clack references from: $SOURCE_PATH"
echo "Docs: $DOC_COUNT, Core source files: $CORE_COUNT, Prompts source files: $PROMPTS_COUNT, Example files: $EXAMPLE_COUNT"
